language: elixir

otp_release:
  - 19.0
  - 19.1
  - 19.2
  - 20.2

elixir:
  - 1.5.0
  - 1.6.0

matrix:
  include:
    - otp_release: 20.2
      elixir: 1.6.0

sudo: false

env:
  - MIX_ENV=test

script: mix test --no-start

notifications:
  recipients:
    - eduardo@gurgel.me
